using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;



public class npcscript : MonoBehaviour
{
    
    private List<string> sceneHistory = new List<string>();  //running history of scenes
    //The last string in the list is always the current scene running

    
    void Start()
    {
        sceneHistory.Add(SceneManager.GetActiveScene().name);
        DontDestroyOnLoad(this.gameObject);  //Allow this object to persist between scene changes
    }
    
    
    void OnTriggerEnter(Collider other )
    {
        if (other.gameObject.tag == "Player")
        {
            LoadScene(SceneManager.GetActiveScene().name);
        }
        
    }

    void Update()
    {
        if (Input.GetKey(KeyCode.Escape))
        {
            PreviousScene();
        }
    }
    
    
    public void LoadScene(string newScene)
    {
        sceneHistory.Add(newScene);
        SceneManager.LoadScene(newScene);
    }
 
    //Call this whenever you want to load the previous scene
    //It will remove the current scene from the history and then load the new last scene in the history
    //It will return false if we have not moved between scenes enough to have stored a previous scene in the history
    public bool PreviousScene()
    {
        bool returnValue = false;
        if (sceneHistory.Count >= 2)  //Checking that we have actually switched scenes enough to go back to a previous scene
        {
            returnValue = true;
            sceneHistory.RemoveAt(sceneHistory.Count -1);
            SceneManager.LoadScene(sceneHistory[sceneHistory.Count -1]);
        }
 
        return returnValue;
    }
}
